name: braille_brigde
description: App para controle de Display Braille via Bluetooth com ESP32
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  lottie: ^3.3.1
  flutter_animate: ^4.5.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
