name: braille_bridge_v2
description: BrailleBridge Versão 2 - Conexão BLE e envio de texto Braille
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
